/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "grover01.v:2" *)
module grover01(A, B, valid);
  wire _0_;
  (* src = "grover01.v:3" *)
  input A;
  (* src = "grover01.v:3" *)
  input B;
  (* src = "grover01.v:9" *)
  wire [3:0] total_value;
  (* src = "grover01.v:13" *)
  wire [3:0] total_weight;
  (* src = "grover01.v:4" *)
  output valid;
  assign _0_ = ~A;
  assign valid = _0_ & B;
  assign total_value = { B, 1'b0, A, B };
  assign total_weight = { A, 1'b0, B, A };
endmodule
