/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "multi.v:2" *)
module multi(A, B, C, D, E, F, valid);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "multi.v:3" *)
  input A;
  (* src = "multi.v:3" *)
  input B;
  (* src = "multi.v:3" *)
  input C;
  (* src = "multi.v:3" *)
  input D;
  (* src = "multi.v:3" *)
  input E;
  (* src = "multi.v:3" *)
  input F;
  (* src = "multi.v:9" *)
  wire [5:0] total_value;
  (* src = "multi.v:4" *)
  output valid;
  assign _2_ = C & D;
  assign _3_ = _2_ & E;
  assign _0_ = ~(F | A);
  assign _1_ = _0_ & B;
  assign valid = _1_ & _3_;
  assign total_value[0] = D;
endmodule
