/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "grover_compare10.v:1" *)
module grover_compare10(A, B, valid);
  wire _0_;
  (* src = "grover_compare10.v:2" *)
  input A;
  (* src = "grover_compare10.v:2" *)
  input B;
  (* src = "grover_compare10.v:3" *)
  output valid;
  assign _0_ = ~B;
  assign valid = A & _0_;
endmodule
